//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeoffice_Decider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ugynokok1Entities : DbContext
    {
        public Ugynokok1Entities()
            : base("name=Ugynokok1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beosztasok> Beosztasok { get; set; }
        public virtual DbSet<Munkak> Munkak { get; set; }
        public virtual DbSet<Ugynokok> Ugynokok { get; set; }
    }
}
