//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeoffice_Decider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugynokok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ugynokok()
        {
            this.Munkaks = new HashSet<Munkak>();
        }
    
        public int ugynok_sk { get; set; }
        public string nev { get; set; }
        public string beosztas_fk { get; set; }
    
        public virtual Beosztasok Beosztasok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Munkak> Munkaks { get; set; }
    }
}
